### ISSUE TITLE
`eventstore` benchmark fills up `/tmp`

### ISSUE THREAD

**Issue by lewurm** [xamarin/benchmarker#25]
I'm not exactly sure if it's the client or server (I suspect the latter), but both don't have an option to control something related to that (at least that's what I see in `--help`). @schani suggested to implement a feature that supports post hooks, that essentially is just a shell script that can do that cleanup.

**Comment by vkargov** [comment]
Confirmed, the server uses /tmp/EventStore as a place to store its logs. I'm looking into how much disabling logs would affect the test's performance.

**Comment by lewurm** [comment]
is there an option to disable logs?

**Comment by vkargov** [comment]
Yes, by passing an additional argument --mem-db to the test and disabling all written logs in NLog.config. I'm currently checking if the logless version is performing any faster than the current version, and whether that would skew the performance data on the test.
(I am inclined to think disabling any hard drive activity would be beneficial in the longer run either way, though.)

**Comment by lewurm** [comment]
For benchmarking purposes we should just switch over to `--mem-db` then anyway.

**Comment by lewurm** [comment]
see #26

**Comment by lewurm** [comment]
when I pass `--mem-db` the server still creates files in `/tmp`

**Comment by vkargov** [comment]
+ #27

**Comment by lewurm** [comment]
fixed by #26 and #27
